// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMlgt8Gj06P9AXv9VJzDt1kys3rDKPrLE',
    appId: '1:626806497029:web:f4408714b80108c8cae16c',
    messagingSenderId: '626806497029',
    projectId: 'diabin-db555',
    authDomain: 'diabin-db555.firebaseapp.com',
    storageBucket: 'diabin-db555.firebasestorage.app',
    measurementId: 'G-886QBQYVEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtx0SBK_9pVAMcXdHZd3DB3bti_62mbQQ',
    appId: '1:626806497029:android:4c382d6e1265ad98cae16c',
    messagingSenderId: '626806497029',
    projectId: 'diabin-db555',
    storageBucket: 'diabin-db555.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYcxtnLsI2LLfCaD3pzC8lruNwp9FCqTA',
    appId: '1:626806497029:ios:db0e2805d198ce03cae16c',
    messagingSenderId: '626806497029',
    projectId: 'diabin-db555',
    storageBucket: 'diabin-db555.firebasestorage.app',
    iosBundleId: 'com.example.diabin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYcxtnLsI2LLfCaD3pzC8lruNwp9FCqTA',
    appId: '1:626806497029:ios:db0e2805d198ce03cae16c',
    messagingSenderId: '626806497029',
    projectId: 'diabin-db555',
    storageBucket: 'diabin-db555.firebasestorage.app',
    iosBundleId: 'com.example.diabin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMlgt8Gj06P9AXv9VJzDt1kys3rDKPrLE',
    appId: '1:626806497029:web:ee30c8c71cbe2c24cae16c',
    messagingSenderId: '626806497029',
    projectId: 'diabin-db555',
    authDomain: 'diabin-db555.firebaseapp.com',
    storageBucket: 'diabin-db555.firebasestorage.app',
    measurementId: 'G-FZBJ9G92LS',
  );
}
